[package]
name = "arrata_app"
version = "0.0.0"
description = "An application for handling Arrata character sheets."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { default-features = false, version = "1.0.196" }
serde_json = { default-features = false, version = "1.0.113" }
dioxus-free-icons = { version = "0.7.0", features = ["bootstrap"] }
rand = { version = "0.8.5" }

[dependencies.dioxus]
version = "0.4.3"
default-features = false

[target.'cfg(not(target_family="wasm"))'.dependencies]
native-dialog = "0.7.0"
dioxus-desktop = { version = "0.4.3", default-features = false, features = [ "tokio_runtime" ] }

[target.'cfg(target_family="wasm")'.dependencies]
dioxus-web = "0.4.3"
getrandom = { version = "0.2.12", features = [ "js" ] }

[[bin]]
name = "arrata_character_sheet_manager"
path = "src/main.rs"

[profile.dev]
lto = "off"
incremental = true

[profile.release]
opt-level = 3
lto = true
incremental = false
codegen-units = 1
panic = "abort"
strip = "symbols"
