[package]
name = "arrata_app"
version = "0.1.0"
description = "An application for handling Arrata character sheets."
edition = "2021"

#[package.metadata.bundle]
#name = "Arrata_Character_Sheet_Manager"
#identifier = "io.github.kalebvonburris.Arrata-APP"
#icon = ["public/rat.png"]
#resources = ["public/*"]
#vesion = "0.1.0"
#category = "Utility"
#short_description = "An application for handling Arrata character sheets."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
serde = "1.0.194"
serde_json = "1.0.111"
tokio = "1.35.1"
dioxus-free-icons = { version = "0.7.0", features = ["font-awesome-brands"] }
lodepng = "3.9.2"
rgb = "0.8"

[dependencies.native-dialog]
version = "0.7.0"
features = ["windows_dpi_awareness", "windows_visual_styles"]

[[bin]]
name = "arrata_character_sheet_manager"
path = "src/main.rs"

[profile.release]
opt-level = 3
