cargo-features = ["panic-immediate-abort"]

[package]
name = "arrata_app"
edition = "2024"
authors = ["Kaleb Burris <kaleb.r.burris@gmail.com>"]
version = "0.0.0"
description = "An application for handling Arrata character sheets."
repository = "https://github.com/Arrata-TTRPG/Arrata-APP"
keywords = ["character-sheet", "ttrpg", "dioxus", "app"]
categories = ["game", "ttrpg", "dioxus"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0.149", default-features = false }
dioxus = { version = "0.7.10", default-features = false, features = [
  "minimal",
  "asset",
  "document",
  "mounted",
  "web",
] }
semver = { version = "1.0.28", default-features = false }
bitcode = { version = "0.6.9", default-features = false }
base64 = { version = "0.23.1", default-features = false, features = ["alloc"] }
getrandom = { version = "0.4.3", features = ["wasm_js"] }
urlencoding = { version = "2.1.3" }
gloo-storage = { version = "0.4.0" }
gloo-timers = { version = "0.4.0", features = ["futures"] }
thousands = { version = "0.2.0", default-features = false }
dioxus-sdk = { version = "0.7.0", features = ["storage"] }
wasm-bindgen = "=0.2.127"
dioxus-free-icons = { version = "0.10.0", features = ["bootstrap"] }
tracing = "0.1.44"
reqwest = { version = "0.13.4", default-features = false }

[dependencies.arrata-lib]
git = "https://github.com/Arrata-TTRPG/Arrata-LIB"
branch = "main"
features = ["dioxus"]

[profile.release]
opt-level = 'z'
panic = 'immediate-abort'
debug = false
lto = true
codegen-units = 1
strip = false

[profile.wasm-release]
inherits = "release"

[profile.release.package."*"]
opt-level = 'z'
debug = false

[profile.wasm-dev]
inherits = "dev"
opt-level = 1
