[package]
name = "arrata_app"
version = "0.0.0"
description = "An application for handling Arrata character sheets."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { default-features = false, version = "1.0.198" }
serde_json = { default-features = false, version = "1.0.116" }
dioxus-free-icons = { version = "0.8.3", features = ["bootstrap"] }
rand = { version = "0.8.5" }
dioxus = "0.5.1"

# Desktop dependencies
native-dialog = { version = "0.7.0", optional = true }

# Web dependencies
getrandom = { version = "0.2.14", optional = true }

[[bin]]
name = "arrata_character_sheet_manager"
path = "src/main.rs"

[features]
web = ["dioxus/web", "getrandom/js"]
desktop = ["dioxus/desktop", "dep:native-dialog"]\

[profile.dev]
lto = "off"
incremental = true

[profile.release]
opt-level = 3
lto = true
incremental = false
codegen-units = 1
panic = "abort"
strip = "symbols"
