cargo-features = ["profile-rustflags"]

[unstable]
profile-rustflags = true

[package]
name = "arrata_app"
version = "0.0.0"
description = "An application for handling Arrata character sheets."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { default-features = false, version = "0.4.3" }
dioxus-desktop = { features = ["tokio_runtime"], default-features = false, version = "0.4.3" }
serde = { default-features = false, version = "1.0.194" }
serde_json = { default-features = false, version = "1.0.111" }
tokio = "1.35.1"
dioxus-free-icons = { version = "0.7.0", features = ["bootstrap"] }
lodepng = { features = ["rust_backend"], default-features = false, version = "3.9.2" }
rgb = { default-features = false, version = "0.8" }

[dependencies.native-dialog]
version = "0.7.0"
features = ["windows_dpi_awareness", "windows_visual_styles"]

[[bin]]
name = "arrata_character_sheet_manager"
path = "src/main.rs"

[profile.dev]
lto = "off"
incremental = true
rustflags = ["-Z", "threads=8"]

[profile.release]
opt-level = 3
lto = "thin"
incremental = false
codegen-units = 1
panic = "abort"
