[package]
name = "arrata_app"
edition = "2021"
version = "0.0.0"
description = "An application for handling Arrata character sheets."

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
lodepng = "3.9.2"
serde = "1.0.194"
serde_json = "1.0.111"
tokio = "1.35.1"

[dependencies.dioxus-free-icons]
version = "0.7.0"
features = ["bootstrap"]

[dependencies.native-dialog]
version = "0.7.0"
features = ["windows_dpi_awareness", "windows_visual_styles"]

[dependencies.rgb]
version = "0.8"
features = []
default-features = false

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1

[profile.release.package]

[profile.dev]
lto = "thin"

[profile.dev.package]

[[bin]]
path = "src/main.rs"
name = "arrata_character_sheet_manager"
required-features = []
