[package]
name = "arrata_app"
edition = "2021"
version = "0.0.0"
description = "An application for handling Arrata character sheets."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { default-features = false, version = "1.0.204" }
serde_json = { default-features = false, version = "1.0.120" }
dioxus-free-icons = { version = "0.8.6", features = ["bootstrap"] }
rand = { version = "0.8.5" , default-features = false }
dioxus = { default-features = false, version = "0.5.1" }
log = "0.4.22"
rfd = "0.14.1"

# Web dependencies
getrandom = { version = "0.2.15", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
urlencoding = { version = "2.1.3", optional = true }

[dependencies.arrata-lib]
git = "https://github.com/Arrata-TTRPG/Arrata-LIB"
branch = "main"

[[bin]]
name = "arrata_character_sheet_manager"
path = "src/main.rs"

[features]
desktop = ["dioxus/desktop"]
web = ["dioxus/web", "getrandom/js", "dep:wasm-logger", "dep:urlencoding"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.release.package]

[profile.release.build-override]
codegen-units = 1
debug = false
opt-level = "z"
strip = "symbols"
