[package]
name = "arrata_app"
version = "0.1.0"
description = "An application for handling Arrata character sheets."
edition = "2021"

[package.metadata.bundle]
name = "ArrataCharacterSheetManager"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.2"
dioxus-desktop = "0.3.0"
serde = "1.0.178"
serde_json = "1.0.104"
tokio = "1.29.1"

[[bin]]
name = "Arrata-Character-Sheet-Manager"
path = "src/main.rs"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = true
panic = 'abort'
