[application]

# App (Project) Name
name = "Arrata Character Sheet Manager"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "desktop"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "assets"

[bundle]
resources = ["assets/*"]

[web.app]

# HTML title tag content
title = "Arrata"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

# uncomment line below if using Router
# index_on_404 = true

# include `assets` in web platform
[web.resource]

# CSS style file
style = ["tailwind.css"]

# Javascript code file
script = []

[web.resource.dev]

# CSS style file
style = []

# Javascript code file
script = []

icon = ["assets/rat.png"]