[application]

# App (Project) Name
name = "arrata-app"

# `build` & `serve` dist path
out_dir = "dist"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = "Arrata Character Sheet Manager"

# Base path for GitHub Pages
#base_path = "Arrata-APP"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "public"]

[bundle]
# Bundle publisher
publisher = "Kaleb Burris"

# Bundle icon
icon = ["rat.png"]
