[build]
target = 'x86_64-unknown-linux-gnu'
rustflags = [
    "-Clto",
    "-Zlocation-detail=none",
    "-Zvirtual-function-elimination"
]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]
