on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_INCREMENTAL: 1

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Cargo Verify
jobs:
  checks:
    name: Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
      - uses: rui314/setup-mold@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsoup2.4 javascriptcoregtk-4.0 -y
          sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev -y
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli --no-confirm --force
      - name: Test build Desktop
        run: dx build --platform desktop
      - name: Test build Web
        run: dx build --platform web
      - name: Cargo Check
        run: cargo check --all
      - name: Cargo Test
        run: cargo test --all
      - name: Cargo Clippy
        run: cargo clippy --all
