on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-verify.yaml
  pull_request:
    branches: ["main"]
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-verify.yaml

env:
  CARGO_INCREMENTAL: 1

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Run Rust checks across all platforms
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Restore Nix cache
        uses: nix-community/cache-nix-action/restore@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}-ci
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}-ci
            nix-${{ runner.os }}-
          paths: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Fix permissions
        continue-on-error: true
        run: |
          sudo chmod 777 ~/.cargo/**
          sudo chmod 777 target/**
      - name: Build tailwindcss
        run: nix develop -c tailwindcss build -i input.css -o public/tailwind.css
      - name: dx build
        run: nix develop -c dx build --platform web
      - name: Cargo Check
        run: nix develop -c cargo check --all
      - name: Cargo Test
        run: nix develop -c cargo test --all
      - name: Cargo Clippy
        run: nix develop -c cargo clippy --all
      - name: Cargo fmt
        run: nix develop -c cargo fmt -- --check

      - name: Save cache
        if: always()
        uses: nix-community/cache-nix-action/save@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}-ci
          paths: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
