# Thanks to https://github.com/NiklasEi/bevy_game_template/blob/main/.github/workflows/release.yaml for much of this code
on:
  push:
    branches: ["main"]
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-verify.yaml
  pull_request:
    branches: ["main"]
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/cargo-verify.yaml

env:
  CARGO_INCREMENTAL: 1
  NODE_VERSION: 20

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Run Rust checks across all platforms
jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - name: Restore Nix cache
        id: restore-nix-cache
        uses: nix-community/cache-nix-action/restore@v7
        with:
          primary-key: nix-${{ runner.os }}-ci
          paths: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Build tailwindcss
        run: nix develop -c tailwindcss build -i input.css -o public/tailwind.css
      - name: dx build
        run: nix develop -c dx build --platform web
      - name: Cargo Check
        run: nix develop -c cargo check --all
      - name: Cargo Test
        run: nix develop -c cargo test --all
      - name: Cargo Clippy
        run: nix develop -c cargo clippy --all
      - name: Cargo fmt
        run: nix develop -c cargo fmt -- --check

      - name: Save cache
        if: always() && steps.restore-nix-cache.outputs.hit-primary-key != 'true'
        uses: nix-community/cache-nix-action/save@v7
        with:
          primary-key: nix-${{ runner.os }}-ci
          paths: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
