# Thanks to https://github.com/NiklasEi/bevy_game_template/blob/main/.github/workflows/release.yaml for much of this code
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_INCREMENTAL: 1

permissions: write-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Run Rust checks across all platforms
jobs:
  check-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy, rust-src
          target: wasm32-unknown-unknown
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsoup2.4 javascriptcoregtk-4.0 -y
          sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev libxdo-dev -y
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Binstall Dioxus-CLI
        run: cargo binstall dioxus-cli --no-confirm
      - name: Enable .cargo
        run: mv .cargo-disabled .cargo
      - name: dx build
        run: dx build --platform desktop --release
      - name: Cargo Check
        run: cargo check --all --release
      - name: Cargo Test
        run: cargo test --all --release
      - name: Cargo Clippy
        run: cargo clippy --all --release
      - name: Cargo fmt
        run: cargo fmt -- --check --release

  test-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt, clippy, rust-src
        target: wasm32-unknown-unknown
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@main
    - name: Binstall Dioxus-CLI
      run: cargo binstall dioxus-cli --no-confirm
    - name: Enable .cargo
      run: mv .cargo-disabled .cargo
    - name: dx build
      run: dx build --platform desktop --release
    - name: Cargo Check
      run: cargo check --all --release
    - name: Cargo Test
      run: cargo test --all --release
    - name: Cargo Clippy
      run: cargo clippy --all --release
    - name: Cargo fmt
      run: cargo fmt -- --check --release

  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy, rust-src
          target: wasm32-unknown-unknown
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Binstall Dioxus-CLI
        run: cargo binstall dioxus-cli --no-confirm
      - name: Enable .cargo
        run: mv .cargo-disabled .cargo
      - name: dx build
        run: dx build --platform web --release
      - name: Cargo Check
        run: cargo check --all --release
      - name: Cargo Test
        run: cargo test --all --release
      - name: Cargo Clippy
        run: cargo clippy --all --release
      - name: Cargo fmt
        run: cargo fmt -- --check --release
