on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  RUSTFLAGS: "-D warnings -Z threads=8"
  CARGO_INCREMENTAL: 1

permissions: write-all

name: Cargo Verify
jobs:
  checks:
    name: Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsoup2.4 javascriptcoregtk-4.0 -y
          sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev -y
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli --no-confirm
      - name: Cargo Build desktop
        run: cargo build --features desktop
      - name: Cargo build web
        run: dx build --platform web --features web
      - name: Cargo Check
        run: |
          cargo check --verbose --features desktop
          cargo check --verbose --features web
      - name: Cargo Test
        run: |
          cargo test --verbose --features desktop
          cargo test --verbose --features web
      - name: dx fmt
        run: dx fmt --check
      - name: Cargo Clippy
        run: cargo clippy --verbose
