name: Versioning

on:
  pull_request:
    branches:
        - main
    types:
        - closed

env:
  version: 'v0.0.0'

jobs:
  version:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current version
        id: get_version
        run: echo "version=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: Determine version type
        run: |
          export major=$(echo ${{ env.version }} | cut -d '.' -f 1)
          export minor=$(echo ${{ env.version }} | cut -d '.' -f 2)
          export patch=$(echo ${{ env.version }} | cut -d '.' -f 3)

          if [ -n "${{ contains(github.event.pull_request.labels.*.name, 'major') }}" ]; then
            echo "version=${major+1}.0.0" >> $GITHUB_ENV
          elif [ -n "${{ contains(github.event.pull_request.labels.*.name, 'major') }}" ]; then
            echo "version=${major}.${minor+1}.0" >> $GITHUB_ENV
          elif [ -n "${{ contains(github.event.pull_request.labels.*.name, 'patch') }}" ]; then
            echo "version=${major}.${minor}.${patch+1}" >> $GITHUB_ENV
          fi
      - name: Create new tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          tag: ${{ env.version }}
