name: Versioning

on:
  pull_request:
    branches:
        - main
    types:
        - closed

env:
  version: '0.0.0'

jobs:
  version:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump Major
        if: ${{ contains(github.event.pull_request.labels.*.name, 'major') }}
        uses: flatherskevin/semver-action@v1
        with:
          incrementLevel: major
          source: tags

      - name: Bump Minor
        if: ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}
        uses: flatherskevin/semver-action@v1
        with:
          incrementLevel: minor
          source: tags

      - name: Bump Patch
        if: ${{ contains(github.event.pull_request.labels.*.name, 'patch') }}
        uses: flatherskevin/semver-action@v1
        with:
          incrementLevel: patch
          source: tags
