# Thanks to https://github.com/NiklasEi/bevy_game_template/blob/main/.github/workflows/release.yaml for much of this code
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'V*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version - in the form of v1.2.3'
        required: true
        type: string

env:
  EXECUTABLE_NAME: "arrata_character_sheet_manager"
  NODE_VERSION: 18

permissions: write-all

name: Create release
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ inputs.version || steps.tag.outputs.tag }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: get-version
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose --latest
        env:
          OUTPUT: CHANGELOG.md
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body_path: ${{ steps.git-cliff.outputs.changelog }}
          draft: false
          prerelease: false

  build-linux:
    runs-on: ubuntu-latest
    needs: [get-version, create-release]
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Add mold linker
        uses: rui314/setup-mold@v1
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install libsoup2.4 javascriptcoregtk-4.0 -y
          sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev clang -y
      - name: Build release
        run: cargo build --release --features desktop
      - name: Prepare release
        run: |
          strip target/release/${{ env.EXECUTABLE_NAME }}
          chmod +x target/release/${{ env.EXECUTABLE_NAME }}
          mv target/release/${{ env.EXECUTABLE_NAME }} .
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Create CSS
        run: |
          npm install -D tailwindcss
          npx tailwindcss -i input.css -o public/tailwind.css --minify
      - name: Bundle release
        run: |
          tar -czf ${{ env.EXECUTABLE_NAME }}_linux.tar.gz ${{ env.EXECUTABLE_NAME }} public
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.EXECUTABLE_NAME }}_linux.tar.gz
          asset_name: ${{ env.EXECUTABLE_NAME }}_${{ env.VERSION }}_linux.tar.gz
          release_name: ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          overwrite: true

  build-windows:
    runs-on: windows-latest
    needs: [get-version, create-release]
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2
    - name: Build release
      run: |
        cargo build --release --features desktop
        cp target/release/${{ env.EXECUTABLE_NAME }}.exe .
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.NODE_VERSION }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - name: Create CSS
      run: |
        npm install -D tailwindcss
        npx tailwindcss -i input.css -o public/tailwind.css --minify
    - name: Zip release
      uses: vimtor/action-zip@v1
      with:
        files: public ${{ env.EXECUTABLE_NAME }}.exe
        dest: ${{ env.EXECUTABLE_NAME }}_windows.zip
        recursive: false
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.EXECUTABLE_NAME }}_windows.zip
        asset_name: ${{ env.EXECUTABLE_NAME }}_${{ env.VERSION }}_windows.zip
        tag: ${{ env.VERSION }}
        overwrite: true

  build-web:
    runs-on: ubuntu-latest
    needs: [get-version, create-release]
    env:
      VERSION: ${{needs.get-version.outputs.version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Merge into web-deployment
        run: |
          git merge web-deployment
      - name: Checkout web-deployment
        uses: actions/checkout@v3
        with:
          ref: 'web-deployment'
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsoup2.4 javascriptcoregtk-4.0 -y
          sudo apt install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev -y
          cargo binstall dioxus-cli --no-confirm
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Create CSS
        run: |
          npm install -D tailwindcss
          npx tailwindcss -i input.css -o public/tailwind.css --minify
      - name: Create WASM with Dioxus CLI
        run: dx build --release --platform web --features web
      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: web-deployment
          folder: docs
          target-folder: docs
          commit-message: "chore(cd): Deploy to GH Pages for v${{ env.VERSION }}"
